services:
  db:
    image: postgres:14
    platform: linux/arm64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database:/var/lib/postgresql/data/
      - ./docker/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - .:/app
    restart: always

volumes:
  database: